### PR TITLE
Update CMIP6 data holdings page for new tables.

### PR DESCRIPTION
**Pull request by mauzey1**

### CODE REVIEW

**Comment by taylor13** [comment]
I'm not sure what has to be done here, but if this makes "live" the recent changes to tables showing CMIP6 data holdings, then I favor it.

**Comment by durack1** [comment]
@taylor13 see that green button.. Feel the power...

**Comment by mauzey1** [comment]
@taylor13 These changes are for removing the <div style="overflow-x:auto;"> tags from index.md since they are now part of the tables made by the new script.  This gives each table its own scroll bar if they are wide.  This PR also updates the example tables stored in the repo.

**Comment by durack1** [comment]
@mauzey1 thanks for this, so we can see these shiny new tables, I just merged the PR

**Comment by taylor13** [comment]
thanks for taking the initiative.  What's the point of me pushing the green button if I can't check what the final product will look like?  Why can't Chris push the green button; he knows what it's going to look like.

**Comment by durack1** [comment]
@taylor13 it's all about trust, and not merging your own PRs..

**Comment by durack1** [comment]
@mauzey1 what is the update frequency for https://pcmdi.llnl.gov/CMIP6/ArchiveStatistics/esgf_data_holdings/? It seems the last run was 16:55, so at 17:11 I assume we'll be waiting an hour or so?

**Comment by taylor13** [comment]
I'd rather trust those who've made the changes to check them out, and if there are not problems, go ahead and merge.  Not sure what added value there is for me to *not* check the changes and give the go-ahead to merge.  Seems like formalism without benefit.

**Comment by durack1** [comment]
@taylor13 a very accurate assessment - @mauzey1 I think we trust you on this one, so feel free to continue making great improvements without requesting reviews from us. I for one am more than happy to provide feedback on the live pages, once they're in place - if you ping us when a PR is merged we can view the changes on the live site

**Comment by mauzey1** [comment]
@durack1 Yes, the script updates every 55 minutes past the hour.  However, I will need to change the script to the new one get the updated tables.  This PR is pending https://github.com/ESGF/esgf-utils/pull/4.

**Comment by durack1** [comment]
@mauzey1 nice work - it's now live!

https://pcmdi.llnl.gov/CMIP6/ArchiveStatistics/esgf_data_holdings/

**Comment by taylor13** [comment]
Very nice indeed.  Thanks!

**Pull request merged**
