### PR TITLE
Add map of CMIP6 contributors to guide page

### PR DESCRIPTION
**Pull request by mauzey1**
Adding @glevava's map to the CMIP6 guide page
#263

### CODE REVIEW

**Comment by durack1** [comment]
@mauzey1 thanks for this, am I right that we'll need to wait for 4:55pm to see the page live?

**Comment by mauzey1** [comment]
@durack1 It's live now on http://pcmdi.github.io/CMIP6/.  It will appear on pcmdi.llnl.gov at 5 PM.

**Comment by durack1** [comment]
@mauzey1 I was just trying to figure out what the template width is - looking at https://github.com/PCMDI/pcmdi.github.io/blob/master/Data/media/css/main.css (I don't know where to look), it seems to me the default iframe sizing of `width="640" height="480"` is a little too small to fit out site template - can we expand this to fit the full page width, and the height to match the width?

**Comment by mauzey1** [comment]
@durack1 Here's the map with the dimensions width="900" and height="540"
screenshot-2019-2-13 cmip6 homepage 3

**Comment by taylor13** [comment]
@mauzey1 If Paul likes it, let's go with the larger size. Thanks.

**Comment by durack1** [comment]
@mauzey1 it seems with these dims we have duplicated globe (South/North America twice), is there another height that will make this fill out better? I'm guessing if the height scales up, then it will attempt to fill the globe once rather than duplicating, no?

**Comment by mauzey1** [comment]
I set the default zoom level to 2 and set the dimensions to width="930" and height="540"
screenshot-2019-2-13 cmip6 homepage 4

**Comment by durack1** [comment]
@mauzey1 yep that's a heap better - this will do great, please revise and we're done and the issue can be closed

**Pull request merged**
