### PR TITLE
Clean up google search box

### PR DESCRIPTION
**Pull request by mauzey1**
Here's an attempt at making the search bar look nicer.  #112

### CODE REVIEW

**Comment by durack1** [comment]
@mauzey1 thanks for addressing this, I was keen to review this - but https://pcmdi.github.io/ doesn't seem to be any different to me? Is there a URL that I can see this change when compared to https://pcmdi.llnl.gov/?

**Comment by durack1** [comment]
@mauzey1 thanks! Is the cronjob still running, it seems the change is yet to propagate to https://pcmdi.llnl.gov/CMIP6/Guide/ - yet..

**Comment by mauzey1** [comment]
@durack1 You will need to clear your browser's cache for the changes to the css to load.

**Comment by durack1** [comment]
Voila! that looks **much** better, thanks!!

**Pull request merged**
