### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by durack1**
@pawpepe @mattben quick typo fix

### CODE REVIEW

**Comment by durack1** [comment]
@pawpepe @mattben it also seems the ` #### [Diagnosis of Climate Models][CMD]` subheading [(line 40)](https://github.com/PCMDI/pcmdi.github.io/edit/master/projects/index.md#L40) doesn't link to anything - can a subpage be created please?

**Comment by durack1** [comment]
@pawpepe @mattben it also seems the `#### [input4MIPs][ICME]` is also home-less (there is no landing page) can you fix that too please?

**Comment by pawpepe** [comment]
@durack1 I just created those 2 pages you asked. Might take couple seconds for the server to update it tho

**Comment by durack1** [comment]
@pawpepe perfect, thanks!

**Pull request merged**
