### PR TITLE
Metrics update 202310

### PR DESCRIPTION
**Pull request by lee1043**
Update interactive plot for MJO metrics with latest calculations

### CODE REVIEW

**Comment by mauzey1** [comment]
@lee1043 Can't we just make research/metrics/index.md be a symlink to latest/index.md to prevent needing to update redundant files?

**Comment by lee1043** [comment]
@mauzey1 I like the idea! Could you please help set it up?

**Comment by lee1043** [comment]
@mauzey1 is the symlink to latest/index.md will be automatically changed to symlink to latest/index.html?

**Comment by mauzey1** [comment]
That's the idea.  However, it doesn't look like it is working as I expected.  I'll need to keep working on it.  I can revert the changes I just submitted if I don't find a solution today.

**Comment by mauzey1** [comment]
My problem turned out that I was running Jekyll in the wrong directory.  The symlink actually works fine.

**Review by mauzey1 — APPROVED** [review]

**Comment by lee1043** [comment]
@mauzey1 Excellent, thank you for the solution!

**Pull request merged**
