### PR TITLE
updated links

### PR DESCRIPTION
**Pull request by taylor13**
Ready to commit.  Please check that link to new data stats table works.

### CODE REVIEW

**Comment by taylor13** [comment]
I don't have time to learn how to change the date.   Can someone else do that please?

**Comment by durack1** [comment]
@taylor13 it's pretty simple, you change the line:
```
###### Document version: 17 October 2018
```
to:
```
###### Document version: 15 January 2019
```

**Comment by taylor13** [comment]
I understand how to edit files, but I don't know where that date is found.  When I find it and change it, then I have to make sure I'm running under bash and invoke something called ???? (can't remember)  before activating jekyll, then review my changes, then commit and push and then do a pull request on github (if I can find where to do that).  Every  time I try to do those steps something doesn't work and I have to call on Charles.  I say we approve the current pull request so users can find the new table.  Maybe next month I'll have time to learn all about git (but I doubt it) and I can change the date.

**Comment by durack1** [comment]
@taylor13 I just edited in the browser directly - see https://github.com/taylor13/pcmdi.github.io/blob/master/CMIP6/index.md

This is now good to go

**Comment by durack1** [comment]
@taylor13 the power is all yours!

**Comment by durack1** [comment]
@taylor13 and changes are in place:
https://pcmdi.llnl.gov/CMIP6/
https://pcmdi.llnl.gov/CMIP6/Guide/dataUsers.html

**Comment by taylor13** [comment]
@durack1     I've got those magic fingers now!

**Comment by durack1** [comment]
@taylor13 heaven help us..

**Pull request merged**
