### PR TITLE
Fix link for esgf-node

### PR DESCRIPTION
**Pull request by sashakames**

### CODE REVIEW

**Comment by durack1** [comment]
@sashakames looks good to me, are there any other instances? We'll also need to tweak [_includes/pcmdi_nav.html](https://github.com/PCMDI/pcmdi.github.io/blob/master/_includes/pcmdi_nav.html#L95)  and [_includes/hero.html](https://github.com/PCMDI/pcmdi.github.io/blob/master/_includes/hero.html#L10) from `http` to `https`

**Comment by durack1** [comment]
@sashakames did you want to add those tweaks to this PR?

**Comment by sashakames** [comment]
its ok to leave http because we redirect.  Until we install the cert https can have issues but http redirects will be ok.

**Comment by durack1** [comment]
@sashakames ok that is merged, as you have the redirect in place it's good to go

**Pull request merged**
