### PR TITLE
Update research/metrics

### PR DESCRIPTION
**Pull request by lee1043**
Add mean climate

### CODE REVIEW

**Comment by lee1043** [comment]
@mauzey1 could you please merge this? Thank you.

**Comment by lee1043** [comment]
@mauzey1 thank you. Just curious, how long usually takes the update to appear on the official website (pcmdi.llnl.gov)?

**Comment by mauzey1** [comment]
@lee1043 pcmdi.llnl.gov gets updated every half hour.  It should update at 4:30 PM, but I will just manually update it now.

**Comment by lee1043** [comment]
@mauzey1 good to know. thank you for the update.

**Pull request merged**
