### PR TITLE
Update index.md for MJO figure description

### PR DESCRIPTION
**Pull request by kristinchang3**
updating MJO interactive bar chart figure description for updated color palette. (Issue: https://github.com/PCMDI/PCMDI_Simulation_Summaries/issues/47)

### CODE REVIEW

**Comment by kristinchang3** [comment]
Hi @lee1043 opening a new PR with the updated MJO interactive bar chart. Could you please review the change when you get a chance? Thanks!

**Comment by lee1043** [comment]
@kristinchang3 The linked page (https://pcmdi.llnl.gov/pmp-preliminary-results/interactive_plot/mjo/bar_chart/mjo_ewr_cmip5and6_overlap_runs_average_v20240329.html) is not opening. Maybe you need to update its permission in the webserver.

**Comment by kristinchang3** [comment]
@lee1043 sorry about that - just updated the permissions!

**Review by lee1043 — APPROVED** [review]

**Comment by lee1043** [comment]
@kristinchang3 thanks for the update!
@mauzey1 thanks for pinging me. I am merging this.

**Pull request merged**
