### PR TITLE
Add ESGF outage placeholder page

### LINKED ISSUE #537: Create temp landing page while ESGF COG outage continues
https://esgf-node.llnl.gov/ is not responsive, and is currently being rebuilt. Need to create a temporary landing page so that traffic to https://esgf-node.llnl.gov/ can be caught and redirected to metagrid (https://aims2.llnl.gov/search)

### PR DESCRIPTION
**Pull request by durack1**
Fix #537

@mauzey1 please review and merge if suitable

@sashakames ping

### CODE REVIEW

**Review by sashakames — COMMENTED** [review]
Remove aims2, it won't have working search while esgf-node is offline.

**Comment by sashakames** [comment]
@mauzey1 Do we have an LLNL footer with the legal, stuff etc we can tack on?

**Comment by durack1** [comment]
> Remove aims2, it won't have working search while esgf-node is offline.

Done in the updated PR

**Comment by durack1** [comment]
> @mauzey1 Do we have an LLNL footer with the legal, stuff etc we can tack on?

This should come for free with the PCMDI page templates - which have a header and footer

**Review by sashakames — APPROVED** [review]

**Pull request merged**
