### PR TITLE
syntax correction for jefferson9

### PR DESCRIPTION
**Pull request by durack1**
@mattben the previous merge didn't follow the correct syntax - see http://pcmdi.github.io/staff.html

### CODE REVIEW

**Comment by mattben** [comment]
lol I even looked at it, good catch!

**Comment by durack1** [comment]
@mattben an nope, my tweaks didn't solve it.. It seems the jefferson entry needs another page generated, so:
```
[hoang]: about/staff/hoang/index.html
[jefferson]: about/staff/jefferson/index.html
[nadeau]: about/staff/nadeau/index.html
```
and the `[Jefferson, Angela][]` replaced with `[Jefferson, Angela][jefferson]` once the above is in place

**Comment by pawpepe** [comment]
I just created a profile page for Angela and emailed her asking to double check her info up there and to provide me with a picture.

**Comment by durack1** [comment]
@pawpepe perfect, thanks!

**Comment by durack1** [comment]
@pawpepe great, I don't have a webserver running so am finding it difficult to validate my syntax..

**Comment by mattben** [comment]
@durack1 on you mac I believe you just need to do `gem install jekyll` then if that works and install jekyll, can you test by running `jekyll s` which will serve the site for you at localhost:4000.

also if you just want to test markdown [Mou](http://25.io/mou/) is a great desktop app, or there is a [web based](http://dillinger.io) one as well.

They both will get you ball park as github flavored markdown has a few inconsistencies

**Pull request merged**
