### PR TITLE
Update CMIP5 terms of reference

### LINKED ISSUE #421: Updating CMIP5 terms of use
The information about CMIP5 data usage is now outdated on the site and needs a refresh with details contained in an email from May 2020 below:

From: "Taylor, Karl E."
Date: Thursday, May 21, 2020 at 12:11 PM
Subject: Re: [Re-send] Quick question: Redistribution of modified [unclassified]

Dear Akiko,

I’m sorry for the slow response. All the CMIP5 data is now available for unrestricted use and some of the guidance provided at  
https://pcmdi.llnl.gov/mips/cmip5/terms-of-use.html Is now outdated, so please follow the “Terms of Use” guidance found at https://pcmdi.llnl.gov/CMIP6/TermsOfUse/TermsOfUse6-1.html.  

I am copying members and ex-members of the WCRP committees who oversee CMIP to see if  they are comfortable with the following policy:

You may redistribute data, but please make sure folks that use your “derived data product” are aware of the CMIP6 Terms of Use and that 
1)	CMIP5 data is available for unrestricted use, and
2)	CMIP6 data is governed by the license provided in the header of each data file (and which may differ from one model to the next).  

I would think that your derived data product would be governed by the same licensing restrictions as the original CMIP6 data.

It is essential that your website make clear that the data you plan to distribute is *not* the data that the climate models produced, but has been modified in a way that has not been necessarily approved by the modeling centers (and clearly does not represent the climate actually simulated by the models).  I think your users would appreciate it if you provided prominent links to the main CMIP6 sites (https://pcmdi.llnl.gov/CMIP6 and https://www.wcrp-climate.org/wgcm-cmip/wgcm-cmip6 ) and CMIP5 sites (https://pcmdi.llnl.gov/mips/cmip5/ and https://www.wcrp-climate.org/wgcm-cmip/wgcm-cmip5  ) so they could get additional information about the original data (or download the original data itself). You could also point them to the CMIP6 terms of use document: https://pcmdi.llnl.gov/CMIP6/TermsOfUse/TermsOfUse6-1.html .

Thanks and best regards,
Karl

@taylor13 @matthew-mizielinski ping

### PR DESCRIPTION
**Pull request by durack1**
Fix #421 

@taylor13 @matthew-mizielinski

### CODE REVIEW

**Comment by durack1** [comment]
@mauzey1 please merge this if the format is appropriate

**Comment by taylor13** [comment]
before proceeding, see  issue https://github.com/PCMDI/pcmdi.github.io/issues/421

**Comment by durack1** [comment]
@mauzey1 please ignore this PR for now, we are iterating and I will update once a final PR is ready for review and merging

**Comment by durack1** [comment]
@mauzey1 @taylor13 please review, and if no problems are found, merge this to the master branch

**Review by mauzey1 — APPROVED** [review]

**Comment by durack1** [comment]
@mauzey1 thanks - 15:30 is the next cron update, correct?

**Pull request merged**
